import type { NextPage } from 'next';
import Head from 'next/head';
import { useMemo, useState } from 'react';

import { Header } from '../components/Header';

import { ContainerFirtsContent, Main } from '../styles/Home.styles';

const labels = [
  'UI - User Interface',
  'UX Strategy',
  'UX Writer',
  'UI/UX Developer',
  'Product Design',
  'Usability Testing',
  'UX Research',
];

const Home: NextPage = () => {
  const [label, setLabel] = useState('');

  // useEffect(() => {
  //   setInterval(() => setLabels, 4000);
  // }, []);

  const setLabels = useMemo(() => {
    for (let index = 0; index <= labels.length; index++) {
      setLabel(labels[index]);
      if (index === labels.length) {
        index = 0;
      }
    }
  }, [labels]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <ContainerFirtsContent>
          <Header />
          <div className="content__presentation">
            <h1>
              Olá, Me chamo <br />
              Paulo Nascimento <br />
              <span>{label}.</span>
            </h1>
          </div>
        </ContainerFirtsContent>
      </Main>
    </>
  );
};

export default Home;
